[project]
name = "PAI_2025_Leonard_Aimine_Reconnaissance_faciale_automatiseeV2"
version = "0.1.0"
description = ""

authors = [
    { name = "Aimine Meddeb"},
    { name = " Leonard Beddouk"},

]
requires-python = ">=3.10, <3.14"
readme = "README.md"
dependencies = [
    "pyside6",
    "PyQt6",
    "opencv-python"
]


[project.scripts]
main_qt = "reconnaissance_faciale_automatique.main_qt:run"
webcam = "reconnaissance_faciale_automatique.webcam:main"

[dependency-groups]
test = [
    "pytest",
    "coverage",
    "pandas-stubs",
    "pytest-sugar",
]
docs = [
    "Sphinx",
    "pydata-sphinx-theme",
    "myst-parser",
    "jupyter",
    "nbsphinx",
    "sphinx-copybutton",
    "sphinx-autobuild",
    "ipython",
    "sphinx-favicon",
    "sphinx-argparse",
]

[tool.uv]
default-groups = [
    "test",
    "docs",
]

[tool.hatch.build.targets.sdist]
include = ["reconnaissance_faciale_automatique"]

[tool.hatch.build.targets.wheel]
include = ["reconnaissance_faciale_automatique"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pydoclint]
style = 'google'
arg-type-hints-in-docstring = false
skip-checking-raises = true
allow-init-docstring = true
check-return-types = false
check-yield-types = false

[tool.pytest.ini_options]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "ELLIPSIS"]
addopts = "--import-mode=importlib --doctest-modules"
testpaths = ["test_reconnaissance_faciale_automatique", "reconnaissance_faciale_automatique/manager.py"]
python_files = ["test_*.py", "TEST.py"]

[tool.coverage.run]
source = ["reconnaissance_faciale_automatique"]
